# Dog and Cat Breed Alternatives Mapping
# Used to suggest similar-looking breeds during identification.

BREED_ALTERNATIVES = {
    # --- DOGS ---
    'American Staffordshire Terrier': ['American Pit Bull Terrier', 'American Bully', 'Staffordshire Bull Terrier'],
    'Staffordshire Bull Terrier': ['American Staffordshire Terrier', 'American Pit Bull Terrier', 'American Bully'],
    'Bullmastiff': ['American Bully', 'Boxer', 'Mastiff-type breeds'],
    'Tibetan Mastiff': ['Chow Chow', 'Newfoundland', 'Leonberger'],
    'Chow Chow': ['Tibetan Mastiff', 'Keeshond', 'Pomeranian'],
    'Japanese Spitz': ['American Eskimo Dog', 'Samoyed', 'German Spitz', 'Volpino Italiano', 'White Pomeranian'],
    'American Eskimo Dog': ['Japanese Spitz', 'Samoyed', 'German Spitz', 'Volpino Italiano', 'White Pomeranian'],
    'Samoyed': ['Japanese Spitz', 'American Eskimo Dog', 'White Swiss Shepherd', 'Eurasier', 'Keeshond'],
    'Siberian Husky': ['Alaskan Malamute', 'Samoyed', 'Canadian Eskimo Dog', 'Akita'],
    'Alaskan Malamute': ['Siberian Husky', 'Samoyed', 'Canadian Eskimo Dog', 'Akita'],
    'Golden Retriever': ['Labrador Retriever', 'Flat-Coated Retriever', 'Chesapeake Bay Retriever', 'English Setter'],
    'Labrador Retriever': ['Golden Retriever', 'Flat-Coated Retriever', 'Chesapeake Bay Retriever', 'Weimaraner'],
    'Beagle': ['English Foxhound', 'Harrier', 'American Foxhound', 'Basset Hound'],
    'Doberman Pinscher': ['German Pinscher', 'Manchester Terrier', 'Beauceron', 'Rottweiler'],
    'Whippet': ['Greyhound', 'Italian Greyhound', 'Saluki', 'Borzoi'],
    'Collie': ['Shetland Sheepdog', 'Border Collie', 'Australian Shepherd'],
    'Shetland Sheepdog': ['Collie', 'Border Collie', 'Australian Shepherd'],
    'Pug': ['French Bulldog', 'Boston Terrier', 'Brussels Griffon'],
    'French Bulldog': ['Boston Terrier', 'Pug', 'English Bulldog'],
    'Boston Terrier': ['French Bulldog', 'Pug', 'Staffordshire Bull Terrier'],
    'Basenji': ['Indian Pariah Dog', 'Canaan Dog', 'Carolina Dog', 'Africanis'],
    'Rhodesian Ridgeback': ['Indian Pariah Dog', 'Thai Ridgeback', 'Vizsla', 'Redbone Coonhound'],
    'Indian Pariah Dog': ['Basenji', 'Canaan Dog', 'Carolina Dog', 'Askal/Aspin', 'Soi Dog'],
    'Mixed Breed': ['Mongrel', 'Street Dog', 'Village Dog', 'Mutt'],
    'Bali Dog': ['Indian Pariah Dog', 'Soi Dog', 'Askal/Aspin', 'Basenji'],
    'Formosan Mountain Dog': ['Basenji', 'Indian Pariah Dog', 'Thai Ridgeback'],
    'Great Pyrenees': ['Kuvasz', 'Maremma Sheepdog', 'Akbash Dog', 'Samoyed'],
    'Bernese Mountain Dog': ['Greater Swiss Mountain Dog', 'Appenzeller Sennenhund', 'Entlebucher Sennenhund'],
    'Rottweiler': ['Doberman Pinscher', 'Beauceron', 'Hovawart'],
    'Great Dane': ['Mastiff', 'Irish Wolfhound', 'Greyhound'],

    # --- CATS ---
    'Russian Blue': ['Korat', 'Chartreux', 'British Shorthair (Blue)', 'Nebelung'],
    'Korat': ['Russian Blue', 'Chartreux', 'Burmese (Blue)'],
    'Chartreux': ['British Shorthair (Blue)', 'Russian Blue', 'Korat'],
    'Siamese': ['Thai Cat', 'Tonkinese', 'Balinese', 'Oriental Shorthair'],
    'Thai': ['Siamese', 'Tonkinese', 'Burmese'],
    'Tonkinese': ['Siamese', 'Burmese', 'Thai Cat'],
    'Balinese': ['Siamese', 'Himalayan', 'Javanese'],
    'Persian': ['Himalayan', 'Exotic Shorthair', 'Ragdoll', 'British Shorthair'],
    'Himalayan': ['Persian', 'Siamese', 'Ragdoll', 'Birman'],
    'Exotic Shorthair': ['Persian', 'American Shorthair', 'British Shorthair'],
    'Maine Coon': ['Norwegian Forest Cat', 'Siberian', 'Turkish Angora'],
    'Norwegian Forest Cat': ['Maine Coon', 'Siberian', 'Turkish Van'],
    'Siberian': ['Maine Coon', 'Norwegian Forest Cat', 'Ragdoll'],
    'Abyssinian': ['Somali', 'Singapura', 'Bengal'],
    'Somali': ['Abyssinian', 'Maine Coon', 'Turkish Angora'],
    'Bengal': ['Toyger', 'Savannah', 'Ocicat', 'Egyptian Mau'],
    'Toyger': ['Bengal', 'Egyptian Mau', 'Ocicat'],
    'Savannah': ['Bengal', 'Serval', 'Ocicat'],
    'British Shorthair': ['Scottish Fold', 'Chartreux', 'Exotic Shorthair', 'American Shorthair'],
    'American Shorthair': ['British Shorthair', 'Exotic Shorthair', 'Bombay'],
    'Scottish Fold': ['British Shorthair', 'American Shorthair'],
    'Ragdoll': ['Birman', 'Ragamuffin', 'Himalayan', 'Siberian'],
    'Birman': ['Ragdoll', 'Siamese (Pointed)', 'Himalayan'],
    'Bombay': ['Burmese', 'American Shorthair (Black)'],
    'Burmese': ['Bombay', 'Tonkinese', 'Thai Cat'],
    'Sphynx': ['Peterbald', 'Donskoy', 'Devon Rex'],
    'Devon Rex': ['Cornish Rex', 'Sphynx', 'German Rex'],
    'Cornish Rex': ['Devon Rex', 'Sphynx', 'German Rex'],
    'Egyptian Mau': ['Bengal', 'Ocicat', 'Abyssinian'],
    'Ocicat': ['Bengal', 'Egyptian Mau', 'Abyssinian'],

    # --- CROSSBREEDS & HYBRIDS (from Wikipedia) ---
    'Asian': ['Burmese', 'Chinchilla Persian', 'Oriental Shorthair'],
    'Australian Mist': ['Abyssinian', 'Burmese', 'Domestic Shorthair'],
    'Bambino': ['Munchkin', 'Sphynx'],
    'Birman': ['Siamese', 'Persian', 'Ragdoll'],
    'Burmilla': ['Burmese', 'Chinchilla Persian'],
    'California Spangled': ['Abyssinian', 'American Shorthair', 'British Shorthair', 'Bengal'],
    'Chausie': ['Abyssinian', 'Jungle Cat', 'Oriental Shorthair'],
    'Colorpoint Shorthair': ['Siamese', 'Abyssinian', 'American Shorthair'],
    'Dwelf': ['American Curl', 'Munchkin', 'Sphynx'],
    'Foldex': ['Exotic Shorthair', 'Scottish Fold'],
    'Havana Brown': ['Siamese', 'Burmese', 'Oriental Shorthair (Black)'],
    'Highlander': ['Desert Lynx', 'Jungle Curl'],
    'Javanese': ['Balinese', 'Colorpoint Shorthair', 'Oriental Longhair', 'Siamese'],
    'Kinkalow': ['Munchkin', 'American Curl'],
    'Lambkin': ['Munchkin', 'Selkirk Rex'],
    'Minskin': ['Munchkin', 'Burmese', 'Devon Rex', 'Sphynx'],
    'Minuet': ['Persian', 'Munchkin'],
    'Neva Masquerade': ['Siberian', 'Birman', 'Ragdoll'],
    'Oriental Longhair': ['Oriental Shorthair', 'Balinese', 'Javanese'],
    'Oriental Shorthair': ['Siamese', 'European Shorthair'],
    'Peterbald': ['Donskoy', 'Oriental Shorthair', 'Siamese', 'Balinese'],
    'Ragamuffin': ['Ragdoll', 'Himalayan', 'Persian'],
    'Russian White': ['Russian Blue', 'Siberian'],
    'Snowshoe': ['Siamese', 'American Shorthair'],
    'Tiffanie': ['Burmese', 'Chinchilla Persian', 'Asian'],
    'Toyger': ['Bengal', 'Egyptian Mau'],
    'Ukrainian Levkoy': ['Donskoy', 'Scottish Fold'],
}
